import { useEffect, useRef, useState, type FormEvent } from 'react';
import { useSearchParams, Link } from 'react-router-dom';
import { MapPin, CalendarDays, SlidersHorizontal, ChevronDown, X, Search, GitCompareArrows, Sun, Globe2, Mountain, Waves, Route, Coffee } from 'lucide-react';
import { rides, MONTHS, STYLES, REGIONS } from '../data/rides';
import { filterRides, defaultFilters, type Filters } from '../lib/planning';
import { useStore } from '../lib/store-context';
import { useDocumentMeta, useJsonLd } from '../lib/meta';
import { SITE_DESCRIPTION, absoluteUrl } from '../lib/site';
import { PHOTO_SIZES, heroSrcSet, panoramaSrcSet, ridePhoto, rideSrcSet } from '../lib/images';
import { RideCard } from '../components/RideCard';
import { Modal, Arrow, EmptyState } from '../components/ui';
const styleIcons=[Mountain,Waves,Route,Coffee];
export function Discover(){
 const [params,setParams]=useSearchParams();
 const {compare}=useStore();
 const filters:Filters={...defaultFilters,...Object.fromEntries(Object.keys(defaultFilters).map(key=>[key,params.get(key)||defaultFilters[key as keyof Filters]]))};
 const [query,setQuery]=useState(filters.query),[month,setMonth]=useState(filters.month),[style,setStyle]=useState(filters.style);
 const [filterOpen,setFilterOpen]=useState(false),[draft,setDraft]=useState(filters),[compareMode,setCompareMode]=useState(params.get('compare')==='true'||compare.length>0);
 const resultsRef=useRef<HTMLElement>(null);
 // Filtered views are the same eight rides in another order, so they all
 // canonicalise to the discovery page rather than competing with it.
 useDocumentMeta({description:SITE_DESCRIPTION,path:'/'});
 useJsonLd({'@context':'https://schema.org','@type':'ItemList','name':'Motorcycle routes on ROAM','itemListElement':rides.map((ride,index)=>({'@type':'ListItem',position:index+1,url:absoluteUrl(`/ride/${ride.id}`),name:ride.name}))});
 const active=Object.entries(filters).filter(([key,value])=>key!=='sort'&&!!value);
 const isBrowsing=params.get('all')==='true'||active.length>0;
 const results=filterRides(rides,filters),visible=isBrowsing?results:results.slice(0,3);
 useEffect(()=>{setQuery(filters.query);setMonth(filters.month);setStyle(filters.style);},[filters.query,filters.month,filters.style]);
 function apply(update:Partial<Filters>,all=true){const next={...filters,...update};const search=new URLSearchParams();for(const [key,value]of Object.entries(next))if(value&&!(key==='sort'&&value==='recommended'))search.set(key,value);if(all)search.set('all','true');setParams(search,{preventScrollReset:true});}
 function scrollResults(){setTimeout(()=>resultsRef.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'}),50);}
 function search(event:FormEvent){event.preventDefault();apply({query:query.trim(),month,style});scrollResults();}
 function reset(){setParams(new URLSearchParams('all=true'),{preventScrollReset:true});setQuery('');setMonth('');setStyle('');}
 return <>
 <section className="hero" aria-labelledby="hero-title"><picture><source media="(min-width: 641px)" srcSet={panoramaSrcSet()} sizes={PHOTO_SIZES.full}/><img className="hero-image" src="/images/hero.webp" srcSet={heroSrcSet()} sizes={PHOTO_SIZES.full} fetchPriority="high" alt="A motorcyclist follows a winding road through the Dolomites" width="1536" height="1024"/></picture><div className="container hero-content"><h1 id="hero-title">Life’s better<br/>around the bend.</h1><p>Find your next great ride.<br className="mobile-break"/> We’ll help with the rest.</p><button className="hero-link" onClick={()=>{apply({});scrollResults();}}>Explore the possibilities <Arrow size={22}/></button></div></section>
 <div className="container search-container"><form className="search-panel" onSubmit={search} role="search" aria-label="Find a motorcycle trip"><label className="search-field where-field"><MapPin/><span><span className="field-caption">Where</span><input aria-label="Destination or region" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Anywhere" maxLength={120} list="destinations" autoComplete="off"/><datalist id="destinations">{REGIONS.map(region=><option key={region} value={region}/>)}{rides.map(ride=><option key={ride.id} value={ride.country}>{ride.name}</option>)}</datalist></span>{query?<button type="button" className="clear-search" aria-label="Clear destination" onClick={()=>setQuery('')}><X size={15}/></button>:<ChevronDown className="chevron"/>}</label><label className="search-field"><CalendarDays/><span><span className="field-caption">When</span><select aria-label="Travel month" value={month} onChange={e=>setMonth(e.target.value)}><option value="">Any month</option>{MONTHS.map((m,i)=><option key={m} value={i+1}>{m}</option>)}</select></span><ChevronDown className="chevron"/></label><label className="search-field style-field"><SlidersHorizontal/><span><span className="field-caption">Ride style</span><select aria-label="Ride style" value={style} onChange={e=>setStyle(e.target.value)}><option value="">All roads</option>{STYLES.map(s=><option key={s}>{s}</option>)}</select></span><ChevronDown className="chevron"/></label><button className="button primary search-submit" type="submit">Find my ride <Arrow size={21}/></button></form></div>
 <section className="container discovery" ref={resultsRef} aria-labelledby="destinations-heading"><div className="section-heading"><div><h2 id="destinations-heading">{isBrowsing?'Find your next great ride':<><span className="desktop-heading">Where will the road take you?</span><span className="mobile-heading">Find your next great ride</span></>}</h2><p aria-live="polite">{isBrowsing?`${results.length} extraordinary ${results.length===1?'ride':'rides'}${active.length?' to match your plans':'. A world of possibilities.'}`:'Extraordinary places. Even better rides.'}</p></div>{!isBrowsing?<button className="text-button all-destinations" onClick={()=>{apply({});scrollResults();}}>View all destinations <Arrow/></button>:<label className="sort-control"><span className="sr-only">Sort rides</span><select aria-label="Sort rides" value={filters.sort} onChange={e=>apply({sort:e.target.value})}><option value="recommended">Recommended</option><option value="budget">Lowest daily budget</option><option value="duration">Shortest trip</option><option value="distance">Shortest distance</option></select><ChevronDown size={15}/></label>}</div>
 <div className="discovery-toolbar"><div className="category-tabs" aria-label="Filter by ride type"><button className={`chip ${!filters.style?'active':''}`} onClick={()=>apply({style:''},isBrowsing)}>All rides</button>{STYLES.map((s,i)=>{const Icon=styleIcons[i];return <button className={`chip ${filters.style===s?'active':''}`} key={s} onClick={()=>apply({style:s})}><Icon size={16}/>{s}</button>})}</div><button className={`filter-toggle ${filters.duration||filters.difficulty||filters.budget?'has-filters':''}`} onClick={()=>{setDraft(filters);setFilterOpen(true);}} aria-label="More filters"><SlidersHorizontal size={18}/><span>Filters</span>{[filters.duration,filters.difficulty,filters.budget].filter(Boolean).length>0&&<i>{[filters.duration,filters.difficulty,filters.budget].filter(Boolean).length}</i>}</button></div>
 {active.length>0&&<div className="active-filters">{active.filter(([key])=>key!=='style').map(([key,value])=><button key={key} onClick={()=>apply({[key]:''})}>{key==='month'?MONTHS[Number(value)-1]:key==='budget'?`Up to $${value}/day`:key==='duration'?value==='short'?'2–4 days':value==='week'?'5–7 days':'8+ days':value}<X size={13}/><span className="sr-only">Remove {key} filter</span></button>)}<button className="clear-filters" onClick={reset}>Clear all</button></div>}
 {visible.length?<div className="ride-grid">{visible.map((ride,i)=><RideCard key={ride.id} ride={ride} compareMode={compareMode} priority={i<3}/>)}</div>:<EmptyState title="A different road is waiting" description="No rides match all of those details. Try another month or give yourself a little more room to explore." icon={<Search size={32}/>}><button className="button primary" onClick={reset}>Show all rides <Arrow/></button></EmptyState>}
 {visible.length>0&&<div className="results-footer"><p>Estimates in USD, per rider. Rental, stay, food & fuel included.</p><button className={`text-button ${compareMode?'selected-text':''}`} onClick={()=>setCompareMode(!compareMode)}><GitCompareArrows size={17}/>{compareMode?'Done selecting':'Compare rides'}</button></div>}
 {!isBrowsing&&<button className="mobile-view-all button secondary full" onClick={()=>{apply({});scrollResults();}}>View all destinations <Arrow/></button>}
 </section>
 <section className="season-section"><div className="container season-inner"><div className="season-copy"><span className="section-kicker"><Sun size={17}/> A little timing goes a long way</span><h2>Good roads.<br/>Great timing.</h2><p>Alpine summers. Autumn colours. A warm road in the middle of winter. Find the right place for your time away.</p><div className="season-actions"><label className="season-select"><CalendarDays size={18}/><select aria-label="Explore by month" value={month} onChange={e=>setMonth(e.target.value)}><option value="">Choose a month</option>{MONTHS.map((m,i)=><option key={m} value={i+1}>{m}</option>)}</select><ChevronDown size={16}/></label><button className="button primary" onClick={()=>{apply({...defaultFilters,month});scrollResults();}}>Let’s go <Arrow/></button></div></div><Link to="/ride/lofoten" className="season-image"><img src={ridePhoto('norway')} srcSet={rideSrcSet('norway')} sizes={PHOTO_SIZES.season} alt="A coastal road over the blue water of Lofoten" loading="lazy" width="768" height="512"/><div><span>Long days. Unforgettable detours.</span><strong>Summer in Lofoten <Arrow/></strong></div></Link></div></section>
 <section className="container closing-note"><Globe2 size={28}/><h2>The best souvenir is a good story.</h2><p>Pick a place that moves you. We’ll help you figure out the rest.</p><Link to="/saved" className="text-button">Your someday collection <Arrow/></Link></section>
 <Modal open={filterOpen} onClose={()=>setFilterOpen(false)} title="Find your kind of ride"><div className="filter-form"><fieldset><legend>Time on the road</legend><div className="option-grid">{[['','Any length'],['short','2–4 days'],['week','5–7 days'],['long','8+ days']].map(([value,label])=><button className={`option ${draft.duration===value?'selected':''}`} aria-pressed={draft.duration===value} key={value} onClick={()=>setDraft({...draft,duration:value})}>{label}</button>)}</div></fieldset><fieldset><legend>Riding difficulty</legend><p className="muted small">All routes assume a licensed rider with road experience.</p><div className="option-grid">{['','Easygoing','Moderate','Challenging'].map(value=><button className={`option ${draft.difficulty===value?'selected':''}`} aria-pressed={draft.difficulty===value} key={value} onClick={()=>setDraft({...draft,difficulty:value})}>{value||'Any level'}</button>)}</div></fieldset><label className="form-label">Daily budget per rider<select value={draft.budget} onChange={e=>setDraft({...draft,budget:e.target.value})}><option value="">Any budget</option><option value="100">Up to $100 / day</option><option value="200">Up to $200 / day</option><option value="300">Up to $300 / day</option></select><span className="small muted">USD estimate including rental, room, food, fuel and extras.</span></label><div className="modal-actions"><button className="text-button" onClick={()=>setDraft({...draft,duration:'',difficulty:'',budget:''})}>Reset filters</button><button className="button primary" onClick={()=>{apply({duration:draft.duration,difficulty:draft.difficulty,budget:draft.budget});setFilterOpen(false);scrollResults();}}>Show {filterRides(rides,draft).length} rides <Arrow/></button></div></div></Modal>
 </>;
}
