import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Check, CalendarDays, Users, Bike, Download, Route, Wallet, ListChecks, Plus, MapPin, Coffee, ChevronDown, Trash2, NotebookPen, ExternalLink, FileText, Copy, CircleCheck, Pencil, Info, ArrowUpRight } from 'lucide-react';
import { rideById, type Costs } from '../data/rides';
import { useStore } from '../lib/store-context';
import { addDays, CHECKLIST, downloadFile, formatDate, money, planCalendar, planMarkdown, tripBudget, type PlanDay } from '../lib/planning';
import { uid } from '../lib/id';
import { useDocumentMeta } from '../lib/meta';
import { Arrow, EmptyState, Modal } from '../components/ui';
export function Planner(){
 const {id}=useParams(),store=useStore(),navigate=useNavigate();const trip=store.trips.find(t=>t.id===id);const ride=trip?rideById(trip.rideId):undefined;
 const [tab,setTab]=useState('Itinerary'),[exportOpen,setExportOpen]=useState(false),[deleteOpen,setDeleteOpen]=useState(false),[renameOpen,setRenameOpen]=useState(false),[nameDraft,setNameDraft]=useState('');
 useDocumentMeta({title:trip?trip.name:'Trip not found',description:'Plan your motorcycle trip: itinerary, budget and preparation checklist.',noIndex:true});
 if(!trip||!ride)return <div className="container"><EmptyState title="Let’s find your next adventure" description="This trip isn’t saved in this browser. Start with a ride you love, or return to your other plans." to="/trips" action="Go to my trips"/></div>;
 const update=(patch:Parameters<typeof store.updateTrip>[1])=>store.updateTrip(trip.id,patch);
 const budget=tripBudget(trip),distance=trip.days.reduce((total,day)=>total+day.km,0),outOfSeason=trip.startDate&&!ride.months.includes(Number(trip.startDate.slice(5,7)));
 const updateDay=(dayId:string,patch:Partial<PlanDay>)=>update({days:trip.days.map(day=>day.id===dayId?{...day,...patch}:day)});
 const addRest=(index:number)=>{const days=[...trip.days],previous=days[index];days.splice(index+1,0,{id:uid(),title:`A slow day in ${previous.stay}`,description:'Sleep in, explore on foot, or just enjoy being here. This day is yours.',km:0,stay:previous.stay,notes:'',rest:true});update({days});store.notify('A little breathing room, added.');};
 const exportPlan=()=>{downloadFile(`roam-${ride.id}-trip.md`,planMarkdown(trip,ride),'text/markdown');store.notify('Your trip plan has been downloaded');};
 const exportCalendar=()=>{if(!trip.startDate)return;downloadFile(`roam-${ride.id}.ics`,planCalendar(trip),'text/calendar');store.notify('Calendar file downloaded. Open it in your calendar app.');};
 const copyPlan=async()=>{try{await navigator.clipboard.writeText(planMarkdown(trip,ride));store.notify('Trip plan copied');}catch{store.notify('Copy isn’t available here. Download your plan instead.');}};
 return <div className="container planner-page"><div className="planner-topbar"><Link to="/trips" className="text-button"><ArrowLeft size={19}/>My trips</Link><span className={`autosave ${store.storageError?'error':''}`}>{store.storageError?<Info size={15}/>:<Check size={15}/>}<span>{store.storageError?'Not saved — export a copy':'Saved on this device'}</span></span></div><div className="planner-heading"><div><span className="country">{ride.country} · Your adventure</span><div className="editable-title"><h1>{trip.name}</h1><button className="icon-button" aria-label="Rename trip" onClick={()=>{setNameDraft(trip.name);setRenameOpen(true);}}><Pencil size={17}/></button></div><p>{trip.days.length} days <span>·</span> ~{distance.toLocaleString()} km <span>·</span> {ride.difficulty}</p></div><button className="button secondary" onClick={()=>setExportOpen(true)}><Download size={18}/>Export trip</button></div>
 <div className="planner-layout"><div className="planner-main"><div className="trip-banner"><img src={`/images/${ride.image}.webp`} alt={`${ride.name} landscape`} width="768" height="512"/><div><span>Your story starts here.</span><Link to={`/ride/${ride.id}`}>View the original ride <ArrowUpRight size={16}/></Link></div></div><div className="trip-settings"><label className="form-label"><span><CalendarDays size={16}/>Start date</span><input type="date" value={trip.startDate} onChange={e=>update({startDate:e.target.value})} aria-label="Trip start date"/>{trip.startDate&&<span className="setting-hint">Until {formatDate(addDays(trip.startDate,trip.days.length-1),true)}</span>}</label><label className="form-label"><span><Users size={16}/>Riders</span><select value={trip.riders} onChange={e=>update({riders:Number(e.target.value)})} aria-label="Number of riders">{Array.from({length:12},(_,i)=><option key={i} value={i+1}>{i+1} rider{i?'s':''}</option>)}</select><span className="setting-hint">One motorcycle per rider</span></label><label className="form-label"><span><Bike size={16}/>Your motorcycle</span><select value={trip.ownBike?'own':'rental'} onChange={e=>update({ownBike:e.target.value==='own'})} aria-label="Motorcycle arrangement"><option value="rental">Rent a bike</option><option value="own">Bring my own</option></select><span className="setting-hint">{trip.ownBike?'Rental removed from budget':'Rental included in budget'}</span></label></div>{outOfSeason&&<div className="season-notice"><CalendarDays size={19}/><p>Your dates fall outside our suggested riding months ({ride.season}). Check weather and road access before committing.</p></div>}
 <div className="planner-tabs" role="tablist" aria-label="Trip planning sections">{[{label:'Itinerary',icon:Route},{label:'Budget',icon:Wallet},{label:'Get ready',icon:ListChecks}].map(({label,icon:Icon})=><button role="tab" aria-selected={tab===label} aria-controls="planner-panel" id={`planner-tab-${label.replace(' ','-')}`} key={label} tabIndex={tab===label?0:-1} onKeyDown={e=>{const labels=['Itinerary','Budget','Get ready'];if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?labels[0]:e.key==='End'?labels[2]:labels[(labels.indexOf(tab)+(e.key==='ArrowRight'?1:2))%3];setTab(next);document.getElementById(`planner-tab-${next.replace(' ','-')}`)?.focus();}}} onClick={()=>setTab(label)}><Icon size={18}/>{label}{label==='Get ready'&&<span>{trip.checklist.length}/8</span>}</button>)}</div><div id="planner-panel" role="tabpanel" aria-labelledby={`planner-tab-${tab.replace(' ','-')}`} className="planner-panel">
 {tab==='Itinerary'&&<><div className="section-heading small-heading"><div><h2>The journey is yours.</h2><p>Make room for the moments in between.</p></div></div><div className="planner-days">{trip.days.map((day,i)=><div key={day.id} className="planner-day-wrap"><details className={`planner-day ${day.rest?'rest-day':''}`} open={i===0}><summary><span className="day-number">{day.rest?<Coffee size={19}/>:String(i+1).padStart(2,'0')}</span><span className="planner-day-summary"><span className="day-label">Day {i+1}{trip.startDate&&` · ${formatDate(addDays(trip.startDate,i),true)}`}</span><strong>{day.title}</strong><span className="day-meta">{day.rest?'A day off the bike':`~${day.km} km`}<span>·</span>{day.stay}</span></span><ChevronDown size={18}/></summary><div className="planner-day-content"><p>{day.description}</p><div className="day-edit-grid"><label className="form-label"><span><MapPin size={14}/>Overnight stop</span><input value={day.stay} maxLength={100} onChange={e=>updateDay(day.id,{stay:e.target.value})} aria-label={`Day ${i+1} overnight stop`}/></label>{!day.rest&&<label className="form-label">Approx. distance (km)<input type="number" min="0" max="2000" step="5" value={day.km} onChange={e=>updateDay(day.id,{km:Math.min(2000,Math.max(0,Number(e.target.value)))})} aria-label={`Day ${i+1} distance`}/></label>}</div><label className="form-label"><span><NotebookPen size={14}/>Your notes</span><textarea value={day.notes} onChange={e=>updateDay(day.id,{notes:e.target.value})} rows={3} maxLength={5000} placeholder="A café worth stopping for, your stay, a detour…" aria-label={`Day ${i+1} notes`}/></label><div className="day-actions"><a className="text-button small" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${day.stay}, ${ride.country}`)}`} target="_blank" rel="noreferrer">Explore overnight area <ExternalLink size={14}/></a>{day.rest&&<button className="text-button danger small" onClick={()=>update({days:trip.days.filter(d=>d.id!==day.id)})}><Trash2 size={14}/>Remove rest day</button>}</div></div></details>{trip.days.length<30&&<button className="add-rest" onClick={()=>addRest(i)} aria-label={`Add a rest day after day ${i+1}`}><Plus size={14}/>Add a rest day</button>}</div>)}</div><div className="route-context"><Info size={18}/><p>A flexible sample itinerary, with approximate distances. Use a navigation app and current local information to verify your exact daily route.</p></div><label className="form-label trip-notes"><span><NotebookPen size={18}/>One place for all the little things.</span><textarea value={trip.notes} onChange={e=>update({notes:e.target.value})} rows={4} maxLength={10000} placeholder="Flight details, rental contacts, the café your friend told you about…" aria-label="General trip notes"/></label></>}
 {tab==='Budget'&&<><h2>More clarity. Fewer surprises.</h2><p className="muted">Start with our estimates, then adjust them to your travel style.</p><div className="budget-explainer"><Wallet size={22}/><div><b>All amounts are in USD.</b><p>Daily costs are per rider. We assume one bike and one room per person; change the room cost if you’ll share.</p></div></div><div className="budget-input-list">{([{key:'bike',name:'Motorcycle rental',unit:'per day',icon:Bike},{key:'stay',name:'Accommodation',unit:'per night',icon:MapPin},{key:'food',name:'Food & coffee',unit:'per day',icon:Coffee},{key:'fuel',name:'Fuel',unit:'per riding day',icon:Route},{key:'extras',name:'Experiences & little extras',unit:'per day',icon:SunIcon}] as const).map(({key,name,unit,icon:Icon})=><div className={`budget-input-row ${key==='bike'&&trip.ownBike?'disabled':''}`} key={key}><Icon size={20}/><label htmlFor={`cost-${key}`}><b>{name}</b><span>{key==='bike'&&trip.ownBike?'You’re bringing your own':unit}</span></label><div className="currency-input"><span>$</span><input id={`cost-${key}`} type="number" min="0" max="10000" step="1" disabled={key==='bike'&&trip.ownBike} value={key==='bike'&&trip.ownBike?0:trip.costs[key]} onChange={e=>update({costs:{...trip.costs,[key]:Math.min(10000,Math.max(0,Number(e.target.value)))}})} aria-label={`${name} cost in USD`}/></div></div>)}</div><div className="budget-assumptions"><h3>The details behind the estimate</h3><ul><li>{trip.days.length} trip days, {budget.nights} nights, {trip.days.filter(d=>!d.rest).length} riding days, {trip.riders} rider{trip.riders!==1?'s':''}.</li><li>Rental runs through rest days. Fuel is only counted on riding days.</li><li>A 10% buffer gives you a little breathing room.</li><li>Flights, visas, insurance, security deposits, bike transport and one-way rental fees are extra.</li></ul><p>These are planning estimates, not live prices or quotes. Confirm costs directly with providers.</p></div><button className="text-button" onClick={()=>{update({costs:{...ride.costs} as Costs});store.notify('Original budget estimates restored');}}>Restore suggested costs</button></>}
 {tab==='Get ready'&&<><div className="checklist-heading"><div><h2>Good preparation. Great adventure.</h2><p className="muted">A few things to sort before you turn the key.</p></div><span className="checklist-score">{trip.checklist.length}<small>/ 8</small></span></div><div className="checklist-progress"><i style={{width:`${trip.checklist.length/8*100}%`}}/></div>{trip.checklist.length===8&&<div className="ready-message"><CircleCheck size={26}/><div><h3>You’ve made room for the adventure.</h3><p>Checklist complete. Give the weather and road conditions one last look before departure.</p></div></div>}<div className="checklist">{CHECKLIST.map(item=><label className={`checklist-item ${trip.checklist.includes(item.id)?'checked':''}`} key={item.id}><input type="checkbox" checked={trip.checklist.includes(item.id)} onChange={()=>update({checklist:trip.checklist.includes(item.id)?trip.checklist.filter(x=>x!==item.id):[...trip.checklist,item.id]})}/><span className="custom-checkbox"><Check size={16}/></span><span><strong>{item.title}</strong><span>{item.text}</span></span></label>)}</div><div className="source-block"><h3>Local knowledge goes a long way.</h3><a href={ride.source.url} target="_blank" rel="noreferrer">{ride.source.name}<ExternalLink size={16}/></a></div></>}
 </div></div><aside className="planner-sidebar"><div className="budget-summary"><span className="country">Your trip at a glance</span><h2>{money(budget.total)}</h2><p>Estimated total for {trip.riders} rider{trip.riders!==1?'s':''}</p><div className="budget-breakdown">{[['Motorcycle rental',budget.parts.bike],['Accommodation',budget.parts.stay],['Food & coffee',budget.parts.food],['Fuel',budget.parts.fuel],['Experiences & extras',budget.parts.extras]].map(([label,value])=><div key={label}><span>{label}</span><b>{money(Number(value))}</b></div>)}<div className="buffer-line"><span>A little breathing room <small>10%</small></span><b>{money(budget.buffer)}</b></div></div><div className="summary-total"><span>Estimated total <small>USD</small></span><strong>{money(budget.total)}</strong></div><p className="small muted">{budget.days} days · {budget.nights} nights · {trip.riders} rider{trip.riders!==1?'s':''}</p><button className="button primary full" onClick={()=>setExportOpen(true)}>Take your plan with you <Download size={18}/></button><p className="fine-print">Download your itinerary, budget and checklist. Your next adventure, all in one place.</p></div><div className="planner-side-note"><Coffee size={24}/><h3>Leave a little room.</h3><p>The best moments rarely make the itinerary. A rest day is a good place to start.</p></div><button className="text-button danger delete-trip" onClick={()=>setDeleteOpen(true)}><Trash2 size={15}/>Delete this trip</button></aside></div>
 <Modal open={exportOpen} onClose={()=>setExportOpen(false)} title="Good to go. Wherever you go."><p className="muted">Keep a copy of your trip or share the plan with your riding crew.</p><div className="export-options"><button onClick={exportPlan}><span className="export-icon"><FileText/></span><span><b>Download trip plan</b><small>Itinerary, budget, notes & checklist · Markdown</small></span><Download size={20}/></button><button onClick={exportCalendar} disabled={!trip.startDate}><span className="export-icon"><CalendarDays/></span><span><b>Add to your calendar</b><small>{trip.startDate?'One event for each trip day · ICS':'Set a start date to create calendar events'}</small></span><Download size={20}/></button><button onClick={copyPlan}><span className="export-icon"><Copy/></span><span><b>Copy the whole plan</b><small>Ready to paste into a message or document</small></span><Arrow size={20}/></button></div><p className="fine-print">Your trip stays saved in this browser. A downloaded copy is yours to keep.</p></Modal>
 <Modal open={deleteOpen} onClose={()=>setDeleteOpen(false)} title="Delete this trip?"><p>“{trip.name}” and its notes will be removed from this browser. Download a copy first if you’d like to keep it.</p><div className="modal-actions"><button className="button secondary" onClick={()=>setDeleteOpen(false)}>Keep my trip</button><button className="button danger-button" onClick={()=>{store.deleteTrip(trip.id);navigate('/trips');}}>Delete trip</button></div></Modal>
 <Modal open={renameOpen} onClose={()=>setRenameOpen(false)} title="Give your adventure a name"><form onSubmit={e=>{e.preventDefault();if(nameDraft.trim()){update({name:nameDraft.trim()});setRenameOpen(false);}}}><label className="form-label">Trip name<input autoFocus value={nameDraft} onChange={e=>setNameDraft(e.target.value)} required maxLength={100} placeholder="A week of mountain mornings"/></label><div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setRenameOpen(false)}>Cancel</button><button type="submit" className="button primary" disabled={!nameDraft.trim()}>Save name <Check size={17}/></button></div></form></Modal>
 </div>;
}
function SunIcon({size=20}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/></svg>}
