import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Heart, CalendarDays, MapPin, Route, Bike, Check, ExternalLink, GitCompareArrows, ChevronDown, Sun, Share2 } from 'lucide-react';
import { rideById, dailyCost, MONTHS } from '../data/rides';
import { useStore } from '../lib/store-context';
import { money } from '../lib/planning';
import { Arrow, RideStats, EmptyState, Note } from '../components/ui';
export function RideDetail(){
 const {id}=useParams();const ride=rideById(id||'');const store=useStore(),navigate=useNavigate();const [tab,setTab]=useState('Overview');
 if(!ride)return <div className="container"><EmptyState title="This road isn’t on our map" description="The ride may have moved, or the link may be incomplete. There’s plenty more to explore."/></div>;
 const saved=store.saved.includes(ride.id),compared=store.compare.includes(ride.id);
 const plan=()=>navigate(`/trips/${store.newTrip(ride)}`);
 const share=async()=>{try{await navigator.clipboard.writeText(window.location.href);store.notify('Ride link copied. Send it to your riding crew.');}catch{store.notify('Copy the address from your browser to share this ride.');}};
 return <div className="detail-page"><div className="container detail-topbar"><Link to="/" className="text-button"><ArrowLeft size={20}/><span>Explore rides</span></Link><span className="mobile-detail-title">{ride.name}</span><div className="inline-actions"><button className="text-button detail-share" onClick={share}><Share2 size={17}/>Share</button><button className={`text-button ${saved?'selected-text':''}`} onClick={()=>store.toggleSaved(ride.id)} aria-pressed={saved} aria-label={`${saved?'Unsave':'Save'} ${ride.name}`}><Heart size={19} fill={saved?'currentColor':'none'}/><span>{saved?'Saved':'Save ride'}</span></button></div></div><div className="container detail-hero"><img src={`/images/${ride.image}.webp`} alt={`Scenic landscape along ${ride.name}`} width="1536" height="1024"/><span className="photo-caption">A little inspiration for the road ahead</span></div><div className="container detail-layout"><div className="detail-main"><div className="detail-title"><span className="country">{ride.country}</span><h1>{ride.name}</h1><p>{ride.tagline}</p><RideStats ride={ride}/></div><div className="detail-tabs" role="tablist" aria-label="Trip details">{['Overview','Itinerary','Good to know'].map(t=><button key={t} id={`tab-${t.replaceAll(' ','-')}`} role="tab" aria-selected={tab===t} aria-controls="detail-panel" onClick={()=>setTab(t)} tabIndex={tab===t?0:-1} onKeyDown={e=>{const tabs=['Overview','Itinerary','Good to know'];if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const next=tabs[(tabs.indexOf(tab)+(e.key==='ArrowRight'?1:2))%3];setTab(next);document.getElementById(`tab-${next.replaceAll(' ','-')}`)?.focus();}}}>{t}</button>)}</div><div role="tabpanel" id="detail-panel" aria-labelledby={`tab-${tab.replaceAll(' ','-')}`} className="detail-panel">
 {tab==='Overview'&&<><p className="detail-description">{ride.description}</p><dl className="route-facts"><div><dt><CalendarDays/>Best time</dt><dd>{ride.season}</dd></div><div><dt><Route/>Road type</dt><dd>{ride.road}</dd></div><div><dt><MapPin/>{ride.start===ride.finish?'Start / finish':'Start → finish'}</dt><dd>{ride.start===ride.finish?ride.start:`${ride.start} → ${ride.finish}`}</dd></div><div><dt><Bike/>Recommended bike</dt><dd>{ride.bike}</dd></div></dl><section className="detail-section"><h2>The moments you’ll ride for</h2><ul className="highlights">{ride.highlights.map(h=><li key={h}><span><Check size={17}/></span>{h}</li>)}</ul></section><section className="detail-section"><div className="section-heading small-heading"><h2>Your days, well spent</h2><button className="text-button" onClick={()=>setTab('Itinerary')}>See all {ride.days} days <Arrow size={18}/></button></div><div className="timeline">{ride.itinerary.slice(0,2).map((day,i)=><div className="timeline-day" key={day.title}><span className="timeline-dot"/><span className="day-label">Day {i+1}</span><h3>{day.title}</h3><p>{day.description}</p></div>)}</div></section></>}
 {tab==='Itinerary'&&<><h2>A route with room for you.</h2><p className="muted">A suggested {ride.days}-day journey. Add rest days and make it your own in the planner.</p><div className="timeline full-timeline">{ride.itinerary.map((day,i)=><details className="timeline-day" key={day.title} open={i===0}><summary><span className="timeline-dot"/><span className="day-label">Day {i+1} <span>~{day.km} km</span></span><span className="timeline-summary-title">{day.title}<ChevronDown size={18}/></span></summary><p>{day.description}</p><div className="day-highlight"><Sun size={16}/>{day.highlight}</div><p className="day-stay"><MapPin size={15}/> Overnight in {day.stay}</p></details>)}</div><Note>Sample itinerary and approximate distances, including suggested detours. Check each day’s exact route and road access with a navigation service and local sources before riding.</Note></>}
 {tab==='Good to know'&&<><h2>A little preparation. A better ride.</h2><div className="practical-list">{ride.practical.map((item,i)=><section key={item.title}><span className="practical-number">0{i+1}</span><div><h3>{item.title}</h3><p>{item.text}</p></div></section>)}</div><section className="detail-section"><h3>When to go</h3><div className="month-grid">{MONTHS.map((m,i)=><div key={m} className={ride.months.includes(i+1)?'recommended':''} aria-label={`${m}${ride.months.includes(i+1)?', suggested riding month':''}`}><span>{m.slice(0,3)}</span><i/></div>)}</div><p className="small muted">Green marks our suggested riding months. Weather and access vary by year.</p></section><section className="source-block"><h3>Go a little deeper</h3><a href={ride.source.url} target="_blank" rel="noreferrer">{ride.source.name}<ExternalLink size={16}/></a><p className="small muted">Destination reference checked September 2026. Check current information before departure.</p></section></>}
 </div></div><aside className="detail-sidebar"><div className="planning-card"><span className="country">Make it more than a daydream</span><h2>Your next great ride.</h2><p>Start with the route. Make the rest yours.</p><div className="detail-price"><span>Est.</span> <strong>{money(dailyCost(ride))}</strong><span>/ day</span></div><p className="small muted">Per rider · USD · including bike rental</p><div className="mini-budget">{[['Motorcycle rental',ride.costs.bike],['A place to stay',ride.costs.stay],['Food, fuel & little extras',ride.costs.food+ride.costs.fuel+ride.costs.extras]].map(([label,value])=><div key={label}><span>{label}</span><b>{money(Number(value))}</b></div>)}</div><button className="button primary full" onClick={plan}>Plan this ride <Arrow/></button><button className={`button secondary full ${compared?'compared':''}`} onClick={()=>store.toggleCompare(ride.id)} aria-pressed={compared}>{compared?<Check size={18}/>:<GitCompareArrows size={18}/>} {compared?'Added to comparison':'Compare this ride'}</button><Note>Planning estimates, not live quotes. Edit the budget in your trip. Flights, insurance and one-way fees aren’t included.</Note></div><p className="sidebar-reassurance"><Check size={16}/>Your plan saves as you go. No account needed.</p></aside></div><div className="mobile-plan-bar"><div><span className="small">Est. <strong>{money(dailyCost(ride))} / day</strong></span><span className="muted small">{ride.days} days · ~{ride.distance} km</span></div><button className="button primary" onClick={plan}>Plan this ride <Arrow/></button></div></div>;
}
