import { useState, useEffect } from 'react';
import { NavLink, Link, Outlet, useLocation } from 'react-router-dom';
import { Compass, Heart, Map, UserRound, X, Check, GitCompareArrows, ArrowUpRight } from 'lucide-react';
import { useStore } from '../lib/store-context';
import { Logo, Modal, Arrow } from './ui';
import { ErrorBoundary } from './ErrorBoundary';
export function Shell(){
 const {saved,compare,clearCompare,toast,storageError}=useStore();const location=useLocation();const [profile,setProfile]=useState(false);
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});},[location.pathname]);
 const nav=[{to:'/',label:'Explore',mobile:'Explore',icon:Compass},{to:'/saved',label:'Saved rides',mobile:'Saved',icon:Heart},{to:'/trips',label:'My trips',mobile:'My trips',icon:Map}];
 const inPlanner=location.pathname.startsWith('/trips/');
 return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><div className="header-inner"><Link to="/" aria-label="ROAM home"><Logo/></Link><nav className="desktop-nav" aria-label="Main navigation">{nav.map(item=><NavLink key={item.to} to={item.to} end={item.to==='/'}>{item.label}{item.to==='/saved'&&saved.length>0&&<span className="nav-count">{saved.length}</span>}</NavLink>)}</nav><button className="profile-button" onClick={()=>setProfile(true)} aria-label="Your travel space"><UserRound size={19}/></button></div></header>{storageError&&<div className="storage-warning" role="alert">Your browser couldn’t save these changes. Keep this page open and export your trip to keep a copy.</div>}<main id="main"><ErrorBoundary resetKey={location.pathname}><Outlet/></ErrorBoundary></main><footer className="site-footer"><div className="container footer-inner"><Link to="/" aria-label="ROAM home"><Logo/></Link><p>For the joy of the journey.</p><button className="text-button" onClick={()=>setProfile(true)}>About ROAM <ArrowUpRight size={15}/></button></div><p className="footer-note container">Routes and budgets are planning estimates. Destination imagery is AI-created for inspiration.</p></footer><nav className="mobile-nav" aria-label="Mobile navigation">{nav.map(item=><NavLink key={item.to} to={item.to} end={item.to==='/'}><span className="mobile-nav-icon"><item.icon size={22}/>{item.to==='/saved'&&saved.length>0&&<i>{saved.length}</i>}</span>{item.mobile}</NavLink>)}</nav>{compare.length>0&&location.pathname!=='/compare'&&!inPlanner&&<div className="compare-tray"><GitCompareArrows size={20}/><span><b>{compare.length} ride{compare.length!==1?'s':''}</b> to compare</span><Link to="/compare" className="button primary compact">Compare <Arrow size={18}/></Link><button className="icon-button" aria-label="Clear comparison" onClick={clearCompare}><X size={18}/></button></div>}<div className={`toast ${toast?'visible':''}`} role="status" aria-live="polite">{toast&&<><Check size={18}/><span>{toast}</span></>}</div><Modal open={profile} onClose={()=>setProfile(false)} title="Your little corner of the world"><div className="about-art"><Logo/><span>Good roads ahead.</span></div><p>ROAM is a place to find extraordinary motorcycle rides and turn “one day” into a plan.</p><p>Your saved rides and trips stay in this browser. No account needed. Export a trip to keep a copy or share it with your riding friends.</p><div className="info-box"><b>A little context</b><p>These are curated sample itineraries with approximate distances and editable USD budgets, not live bookings or turn-by-turn routes. Check local road access and arrange travel directly with providers. Landscape images are AI-created illustrations.</p></div><button className="button primary full" onClick={()=>setProfile(false)}>Let’s explore <Arrow/></button></Modal></>;
}
